"""
This type stub file was generated by pyright.
"""

from typing import (
    Any,
    Callable,
    Generic,
    Iterable,
    Type,
    TypeVar,
    Union,
    overload,
)

S = TypeVar("S")
T = TypeVar("T")
ClassifierFunction = Callable[[Type[T]], bool]
SpecFunction = Callable[[Type[T]], Iterable[str]]
FieldsMap = dict[str, Any] | None

class MappingWrapper(Generic[T]):
    def __init__(
        self,
        mapper: Mapper,
        target_cls: Type[T],
    ) -> None: ...
    def map(
        self,
        obj: object,
        *,
        skip_none_values: bool = ...,
        fields_mapping: FieldsMap = ...,
        use_deepcopy: bool = ...,
    ) -> T: ...

class Mapper:
    def __init__(self) -> None: ...
    @overload
    def add_spec(
        self, classifier: Type[T], spec_func: SpecFunction[T]
    ) -> None: ...
    @overload
    def add_spec(
        self,
        classifier: ClassifierFunction[T],
        spec_func: SpecFunction[T],
    ) -> None: ...
    def add_spec(
        self,
        classifier: Union[Type[T], ClassifierFunction[T]],
        spec_func: SpecFunction[T],
    ) -> None: ...
    def add(
        self,
        source_cls: Type[S],
        target_cls: Type[T],
        override: bool = ...,
        fields_mapping: FieldsMap = ...,
    ) -> None: ...
    def map(
        self,
        obj: object,
        *,
        skip_none_values: bool = ...,
        fields_mapping: FieldsMap = ...,
        use_deepcopy: bool = ...,
    ) -> object: ...
    def to(self, target_cls: Type[T]) -> MappingWrapper[T]: ...
