"""
This type stub file was generated by pyright.
"""

Any

__PRIMITIVE_TYPES = ...

def is_sequence(obj: Any) -> bool:
    """Check if object implements `__iter__` method"""
    ...

def is_dictionary(obj: Any) -> bool:
    """Check is object is of type dictionary"""
    ...

def is_subscriptable(obj: Any) -> bool:
    """Check if object implements `__getitem__` method"""
    ...

def object_contains(obj: Any, field_name: str) -> bool: ...
def is_primitive(obj: Any) -> bool:
    """Check if object type is primitive"""
    ...

def is_enum(obj: Any) -> bool:
    """Check if object type is enum"""
    ...
